### ISSUE TITLE
Content overflows narrow (mobile width) screens by 32px

### ISSUE THREAD

**Issue by MartinXPN** [NotionX/react-notion-x#298]
#### Description

Seems like notion pages overflow narrow screens to the right by 32px. 
This seems to be caused by paddings that don't take into account the small screen size:
```css
.notion-page {
    width: var(--notion-max-width);
    padding-left: calc(min(16px, 8vw));
    padding-right: calc(min(16px, 8vw));
    margin: 0 auto;
}

.root {
    --notion-max-width: 720px;
}
```
