### ISSUE TITLE
CSS Core - Navigation bar

### ISSUE THREAD

**Issue by MichaelDevC** [NotionX/react-notion-x#96]
I think there are some problems with the style.css core...
My navigation bar is so glitchy from mobile

The text-overflow is not working and I didn't modify the nav-header from my custom CSS

<img width="647" src="https://user-images.githubusercontent.com/57275048/123512309-10758b80-d687-11eb-8983-659be57d201f.png">

It should be like this from original Notion
<img width="349" alt="image" src="https://user-images.githubusercontent.com/57275048/123512380-5e8a8f00-d687-11eb-97af-fae42a2290de.png">

**Comment by MichaelDevC** [comment]
Solved with this:
```css
.breadcrumb {
   text-overflow: unset;
   overflow: hidden;
 }

 .breadcrumb .title {
   white-space: nowrap;
   overflow: hidden;
   text-overflow: ellipsis;
 }
```
